### ISSUE TITLE
Correção dos textos dos demo components

### ISSUE THREAD

**Issue by pedrovsp** [ericferreira1992/ag-table#2]
É necessário fazer uma correção ortográfica dos textos exibidos nos componentes de demonstração do AgTable. Segue lista de componentes a serem corrigidos:

 [ ] ServerSideComponent
 [ ] ClientSideComponent
 [ ] OthersComponent
 [ ] ServerSideInfinity

**Comment by ericferreira1992** [comment]
Issue concluída. A PR já foi feita. Obrigado pela contribuição @pedrovsp.

The issue is done. The pull request has completed. Thanks for contribution @pedrovsp!
